language:
  - cpp

compiler:
  - gcc

sudo: required

#dist: trusty

notifications:
  email:
    recipients:
      - aswinzwork@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always

before_install: # Use this to prepare the system to install prerequisites or dependencies
  - set +e
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"

install: # Use this to install any prerequisites or dependencies necessary to run your build
  - ./scripts/install_dependencies.sh

before_script: # Use this to prepare your build
  - export CATKIN_WS = ~/catkin_ws/src
  - mkdir -p ~/catkin_ws/src
  - if [ "$TRAVIS" = true ] && [ "CI" = true ]; then mv $TRAVIS_BUILD_DIR CATKIN_WS; fi

script: 
  - # Set up ROS workspace
  - . ./scripts/shared.sh
  - sourceROS
  - cd CATKIN_WS
  - catkin_init_workspace 
  - ls
  - cd ..
  - catkin_make -j8

